### ISSUE TITLE
Pytorch 1.11 Request Again!!!

### ISSUE THREAD

**Issue by umitkacar** [nelson-liu/pytorch-manylinux-binaries#10]
Can you provide Pytorch 1.11 for Tesla K40C?

We are looking forward to it!

**Comment by nelson-liu** [comment]
hey sorry, i've been busy with a bunch of random stuff. i'll try to kick off the build today.

**Comment by umitkacar** [comment]
Awesome! 
Thank you so much.

**Comment by umitkacar** [comment]
Pytorch 1.10 was released. But, I need Pytorch 1.11 for Tesla K40C. Can you build it, as well?

**Comment by nelson-liu** [comment]
yes, i know---it's easier for me to do things one version at a time, so i'll need to work through the rest of 1.10.x before 1.11

**Comment by umitkacar** [comment]
Thank you so much! 
You are awesome !
