### ISSUE TITLE
Pytorch 1.13.1 and Pytorch 2.0 Request for Tesla K40C?

### ISSUE THREAD

**Issue by umitkacar** [nelson-liu/pytorch-manylinux-binaries#12]
Can you provide Pytorch 1.13.1 and Pytorch 2.0 for Tesla K40C?

We are looking forward to it!

**Comment by umitkacar** [comment]
Hi Nelson,

Are you available? I am looking forward to it!

Thank you in advance.

**Comment by nelson-liu** [comment]
Hi @umitkacar , sorry for the delayed response---I'm pretty bogged down until the 20th and likely won't have much time to look into things until then . Sorry for the inconvenience, I'll let you know when I've had a time to take a look at things.

**Comment by umitkacar** [comment]
Hi @nelson-liu 
no worries.
Hope things go well!

**Comment by nelson-liu** [comment]
Hi @umitkacar , it looks like pytorch 2.0 is still on nightly---I'm building 1.13.1 right now, but am hesitant to build 2.0 until an official stable release is announced (looks like the current timeline is March 2023)

**Comment by nelson-liu** [comment]
1.13.1 is now uploaded: https://github.com/nelson-liu/pytorch-manylinux-binaries/releases/tag/v1.13.1

**Comment by umitkacar** [comment]
Thank you so much! You are great!
