### ISSUE TITLE
Feature Request: MacOS binaries?

### ISSUE THREAD

**Issue by godofecht** [nelson-liu/pytorch-manylinux-binaries#16]
I was hoping we could get some MacOS binaries as well. I'm looking for 1.13.1, which seems elusive at the moment.

**Comment by nelson-liu** [comment]
Hi, unfortunately I don't have the bandwidth to do MacOS binaries at this time. Sorry about that 😞

**Comment by godofecht** [comment]
I may be able to do the MacOS binaries on your behalf. How does that sound?

**Comment by nelson-liu** [comment]
that sounds great, i'm sure there's appetite for them! happy to include a link in this repo your MacOS binaries, if you get around to building them
