### ISSUE TITLE
Windows builds ?

### ISSUE THREAD

**Issue by 2blackbar** [nelson-liu/pytorch-manylinux-binaries#6]
Can You compile for win10 ? I cant use gpen with my older gtx 780 despite a lot of cuda cores

**Comment by nelson-liu** [comment]
Hi, unfortunately I don't have the bandwidth to do windows binaries at this time. Sorry about that :disappointed:

**Comment by Suleman-Elahi** [comment]
But sir perhaps you can leave a DIY build script for Windows.
