### ISSUE TITLE
Package index page need HTML doctype

### ISSUE THREAD

**Issue by kielnino** [nelson-liu/pytorch-manylinux-binaries#7]
Thank for this great work. I used it  with

`pip install --user torch==1.9.0+cu111 -f https://nelsonliu.me/files/pytorch/whl/torch_stable.html`

and got the following warning:

> Looking in links: https://nelsonliu.me/files/pytorch/whl/torch_stable.html
warning: missing-index-doctype
>
> × The package index page being used does not have a proper HTML doctype declaration.
╰─> Problematic URL: https://cs.stanford.edu/~nfliu/files/pytorch/whl/torch_stable.html
>
> note: This is an issue with the page at the URL mentioned above.
hint: You might need to reach out to the owner of that package index, to get this fixed. See https://github.com/pypa/pip/issues/10825 for context.

**Comment by nelson-liu** [comment]
thanks for letting me know! i've updated the package index and i think the warning no longer appears.
