### ISSUE TITLE
Pytorch 1.11 Request

### ISSUE THREAD

**Issue by umitkacar** [nelson-liu/pytorch-manylinux-binaries#8]
Can you provide Pytorch 1.11 for Tesla K40C?

Thank you in advance.

**Comment by nelson-liu** [comment]
Yes sorry, I've been a bit busy with other stuff. I'll try to have these up in the next few days.

**Comment by umitkacar** [comment]
We are looking forward to it!

**Comment by umitkacar** [comment]
Thank you so much!
